/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var u=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var r=Object.prototype.hasOwnProperty;var p=(i,e)=>{for(var s in e)o(i,s,{get:e[s],enumerable:!0})},h=(i,e,s,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let l of d(e))!r.call(i,l)&&l!==s&&o(i,l,{get:()=>e[l],enumerable:!(n=u(e,l))||n.enumerable});return i};var m=i=>h(o({},"__esModule",{value:!0}),i);var C={};p(C,{default:()=>t});module.exports=m(C);var a=require("obsidian"),t=class extends a.Plugin{async onload(){this.addCommand({id:"duplicate-line-down",name:"Duplicate line down",editorCallback:e=>{this.duplicateLine(e,"down")}}),this.addCommand({id:"duplicate-line-up",name:"Duplicate line up",editorCallback:e=>{this.duplicateLine(e,"up")}})}duplicateLine(e,s){if(e.somethingSelected()){let n=e.getSelection(),l=e.getCursor("from"),c=e.getCursor("to");s==="down"?(e.replaceSelection(n+n),e.setCursor({line:c.line+(c.line-l.line)+1,ch:c.ch})):(e.replaceSelection(n+n),e.setCursor(l))}else{let n=e.getCursor(),l=e.getLine(n.line);s==="down"?(e.setLine(n.line,l+`
`+l),e.setCursor({line:n.line+1,ch:n.ch})):(e.setLine(n.line,l+`
`+l),e.setCursor({line:n.line,ch:n.ch}))}}onunload(){}};

/* nosourcemap */